//! `Device.X_OptimACS_Reputation.` — the attacker-reputation blocklist.
//!
//! The controller (`nemesis`) distributes a CIDR blocklist to every connected
//! device by SETting `Device.X_OptimACS_Reputation.Feed`. The agent had no such
//! path, so every delivery was refused with
//! `read-only or unknown path: Device.X_OptimACS_Reputation.Feed` and not one
//! address was ever blocked.
//!
//! The controller was right to await the answer rather than assume it. Its own
//! comment records the earlier version reporting `delivered: 1, failed: 0` every
//! minute while the device rejected every message — a fleet-wide rejection that
//! read as perfect health.
//!
//! ## Message shapes
//!
//! ```json
//! {"Delta": {"serial": 42, "add": ["1.2.3.0/24"], "remove": ["5.6.7.8/32"]}}
//! {"List":  {"serial": 42, "entries": ["1.2.3.0/24"], "attribution": ["..."]}}
//! ```
//!
//! `Delta` applies incrementally; `List` replaces the set outright. Serial
//! ordering matters: applying deltas in order reproduces the set, so a delta
//! that arrives out of order is refused rather than applied to the wrong base.
//!
//! ## Why an nftables set
//!
//! The blocklist is thousands of prefixes. A rule per prefix would be a linear
//! scan on every packet; a named set with `flags interval` is a single
//! longest-prefix lookup regardless of size. The set lives in its own table so
//! that flushing it cannot disturb `fw4`, which owns the device's real firewall
//! policy and is regenerated by OpenWrt whenever the config changes.

use serde::Deserialize;
use std::collections::HashMap;
use std::process::Command;
use std::sync::Mutex;

pub type Params = HashMap<String, String>;

/// Our own table, deliberately not `fw4`.
///
/// OpenWrt regenerates `inet fw4` wholesale on any firewall reload, which would
/// silently drop everything added here. A separate table survives that, and a
/// mistake in here cannot break the device's actual firewall.
const TABLE: &str = "inet optim_reputation";
const SET: &str = "blocked";

/// The last serial successfully applied, so out-of-order deltas are detectable.
fn last_serial() -> &'static Mutex<Option<u64>> {
    static S: std::sync::OnceLock<Mutex<Option<u64>>> = std::sync::OnceLock::new();
    S.get_or_init(|| Mutex::new(None))
}

#[derive(Deserialize)]
#[serde(untagged)]
enum Feed {
    Tagged(Tagged),
    /// A bare snapshot, for a publisher that sends the payload unwrapped.
    Bare {
        serial: u64,
        entries: Vec<String>,
    },
}

#[derive(Deserialize)]
enum Tagged {
    Delta {
        serial: u64,
        #[serde(default)]
        add: Vec<String>,
        #[serde(default)]
        remove: Vec<String>,
    },
    List {
        serial: u64,
        #[serde(default)]
        entries: Vec<String>,
        #[serde(default)]
        attribution: Vec<String>,
    },
}

fn nft(args: &[&str]) -> Result<String, String> {
    let out = Command::new("nft")
        .args(args)
        .output()
        .map_err(|e| format!("nft not runnable: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "nft {}: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).to_string())
}

/// Create the table, set and drop rule if they are not already there.
///
/// Idempotent: `nft add` on an existing object succeeds, so this runs on every
/// message rather than tracking whether it has been done. A device that was
/// rebooted, or whose firewall was reloaded, gets the structure back without
/// needing a full snapshot.
fn ensure_structure() -> Result<(), String> {
    nft(&["add", "table", "inet", "optim_reputation"])?;
    // `flags interval` is what makes this a prefix set rather than a list of
    // exact addresses; `auto-merge` collapses overlapping prefixes so a feed
    // that contains both 1.2.3.0/24 and 1.2.3.4/32 does not error.
    nft(&[
        "add",
        "set",
        "inet",
        "optim_reputation",
        SET,
        "{ type ipv4_addr ; flags interval ; auto-merge ; }",
    ])?;
    nft(&[
        "add",
        "chain",
        "inet",
        "optim_reputation",
        "input",
        "{ type filter hook input priority -10 ; policy accept ; }",
    ])?;
    // Matching on saddr only: this feed names attackers, and dropping traffic
    // *to* a listed address would break a subscriber who legitimately visits
    // one.
    let rule = format!("ip saddr @{SET} drop");
    let existing = nft(&["list", "chain", "inet", "optim_reputation", "input"]).unwrap_or_default();
    if !existing.contains(&format!("@{SET}")) {
        nft(&[
            "add", "rule", "inet", "optim_reputation", "input", "ip", "saddr", &format!("@{SET}"),
            "drop",
        ])
        .map_err(|e| format!("{e} (rule: {rule})"))?;
    }
    Ok(())
}

/// Only IPv4 prefixes; the set is `ipv4_addr` typed.
///
/// An address the set cannot hold is skipped rather than failing the whole
/// message: one malformed entry in a feed of thousands should not cost every
/// other prefix in it.
fn usable(cidr: &str) -> bool {
    let c = cidr.trim();
    !c.is_empty() && !c.contains(':') && c.chars().next().is_some_and(|ch| ch.is_ascii_digit())
}

fn add_entries(entries: &[String]) -> usize {
    let list: Vec<&str> = entries
        .iter()
        .map(|s| s.trim())
        .filter(|s| usable(s))
        .collect();
    if list.is_empty() {
        return 0;
    }
    // One call for the whole batch. A call per prefix would be thousands of
    // process spawns on a device with a single slow CPU.
    let elems = format!("{{ {} }}", list.join(", "));
    match nft(&["add", "element", "inet", "optim_reputation", SET, &elems]) {
        Ok(_) => list.len(),
        Err(e) => {
            log::warn!("reputation: add batch failed: {e}");
            0
        }
    }
}

fn remove_entries(entries: &[String]) -> usize {
    let list: Vec<&str> = entries
        .iter()
        .map(|s| s.trim())
        .filter(|s| usable(s))
        .collect();
    if list.is_empty() {
        return 0;
    }
    let elems = format!("{{ {} }}", list.join(", "));
    // A delete of something not present is an error in nft, and a delta that
    // removes an entry we never had is normal after a restart. Logged at debug
    // and not treated as failure.
    match nft(&["delete", "element", "inet", "optim_reputation", SET, &elems]) {
        Ok(_) => list.len(),
        Err(e) => {
            log::debug!("reputation: remove batch (partially) absent: {e}");
            0
        }
    }
}

pub async fn set(_cfg: &crate::config::ClientConfig, path: &str, value: &str) -> Result<(), String> {
    if !path.starts_with("Device.X_OptimACS_Reputation.Feed") {
        return Err(format!("read-only or unknown path: {path}"));
    }

    let feed: Feed = serde_json::from_str(value)
        .map_err(|e| format!("reputation: feed is not valid JSON: {e}"))?;

    ensure_structure()?;

    let (serial, applied, mode) = match feed {
        // A snapshot replaces the set outright, so the old contents go first.
        // Flush and refill rather than diffing: the controller sends a List
        // precisely when it does not trust incremental state.
        Feed::Tagged(Tagged::List {
            serial, entries, ..
        })
        | Feed::Bare { serial, entries } => {
            nft(&["flush", "set", "inet", "optim_reputation", SET])?;
            let n = add_entries(&entries);
            (serial, n, "list")
        }

        Feed::Tagged(Tagged::Delta {
            serial,
            add,
            remove,
        }) => {
            // Deltas only compose in order. Applying one to the wrong base
            // produces a set that matches nothing the controller believes, and
            // does so silently; refusing makes the controller resend a
            // snapshot, which is recoverable.
            if let Some(prev) = *last_serial().lock().unwrap() {
                if serial <= prev {
                    return Err(format!(
                        "reputation: delta serial {serial} is not newer than applied {prev}"
                    ));
                }
            }
            let a = add_entries(&add);
            let r = remove_entries(&remove);
            (serial, a + r, "delta")
        }
    };

    *last_serial().lock().unwrap() = Some(serial);
    log::info!("reputation: applied {mode} serial={serial} entries={applied}");
    Ok(())
}

/// Current state, so the controller can see what the device actually holds.
pub async fn get(_cfg: &crate::config::ClientConfig, path: &str) -> Params {
    let mut m = Params::new();
    if !path.starts_with("Device.X_OptimACS_Reputation") {
        return m;
    }
    let base = "Device.X_OptimACS_Reputation.";

    // Reported so a mismatch between what the controller sent and what the
    // device holds is visible, rather than assumed from a successful SET.
    if let Some(s) = *last_serial().lock().unwrap() {
        m.insert(format!("{base}AppliedSerial"), s.to_string());
    }
    if let Ok(out) = nft(&["list", "set", "inet", "optim_reputation", SET]) {
        let count = out.matches('/').count();
        m.insert(format!("{base}EntryCount"), count.to_string());
        m.insert(format!("{base}Active"), "1".to_string());
    } else {
        m.insert(format!("{base}Active"), "0".to_string());
    }
    m
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ipv6_and_junk_are_skipped_not_fatal() {
        assert!(usable("1.2.3.0/24"));
        assert!(usable("8.8.8.8"));
        assert!(!usable("2001:db8::/32"));
        assert!(!usable(""));
        assert!(!usable("not-an-address"));
    }

    #[test]
    fn a_tagged_list_parses() {
        let v: Feed =
            serde_json::from_str(r#"{"List":{"serial":7,"entries":["1.2.3.0/24"]}}"#).unwrap();
        match v {
            Feed::Tagged(Tagged::List {
                serial, entries, ..
            }) => {
                assert_eq!(serial, 7);
                assert_eq!(entries.len(), 1);
            }
            _ => panic!("expected a List"),
        }
    }

    #[test]
    fn a_tagged_delta_parses() {
        let v: Feed = serde_json::from_str(
            r#"{"Delta":{"serial":9,"add":["1.1.1.0/24"],"remove":["2.2.2.2"]}}"#,
        )
        .unwrap();
        match v {
            Feed::Tagged(Tagged::Delta {
                serial,
                add,
                remove,
            }) => {
                assert_eq!(serial, 9);
                assert_eq!(add.len(), 1);
                assert_eq!(remove.len(), 1);
            }
            _ => panic!("expected a Delta"),
        }
    }
}
