#!/bin/sh
# ac-client dev entrypoint
# Generates dev TLS certs, writes config, and starts ac-client.
#
# Environment variables (all optional — sensible dev defaults):
#   AC_WS_URL          WebSocket URL of ac-server  (default: ws://ac-server:3491/usp)
#   AC_CONTROLLER_ID   Controller endpoint ID       (default: ac-server)
#   AC_MAC_ADDR        Device MAC address           (auto-detected from eth0 if unset)
#   AC_ARCH            Architecture string          (default: x86_64)
#   AC_SYS_MODEL       Model string                 (default: openwrt-dev)
#   AC_ENDPOINT_ID     USP endpoint ID              (auto-built from MAC if unset)
#   AC_LOG_LEVEL       Log verbosity: error/warn/info/debug/trace (default: info)
#   AC_MTP             MTP type: websocket/mqtt/both (default: websocket)
#   AC_MQTT_URL        MQTT broker URL (only needed if MTP=mqtt or both)

set -e

CONF_DIR=/etc/apclient
CONF_FILE=${CONF_DIR}/ac_client.conf

# ── Detect MAC address ────────────────────────────────────────────────────────
if [ -z "${AC_MAC_ADDR}" ]; then
    # Try eth0 first, fall back to any interface that has a MAC
    MAC=$(cat /sys/class/net/eth0/address 2>/dev/null \
        || ip link show | awk '/ether/{print $2; exit}')
    AC_MAC_ADDR="${MAC:-02:00:00:00:00:01}"
fi

# ── USP endpoint ID ───────────────────────────────────────────────────────────
if [ -z "${AC_ENDPOINT_ID}" ]; then
    # Format: proto::mac-based identifier (TR-369 § 8.1)
    CLEAN_MAC=$(echo "${AC_MAC_ADDR}" | tr -d ':' | tr '[:upper:]' '[:lower:]')
    AC_ENDPOINT_ID="proto::openwrt-dev-${CLEAN_MAC}"
fi

# ── Defaults ──────────────────────────────────────────────────────────────────
AC_WS_URL="${AC_WS_URL:-ws://ac-server:3491/usp}"
AC_CONTROLLER_ID="${AC_CONTROLLER_ID:-ac-server}"
AC_ARCH="${AC_ARCH:-x86_64}"
AC_SYS_MODEL="${AC_SYS_MODEL:-openwrt-dev}"
AC_LOG_LEVEL="${AC_LOG_LEVEL:-info}"
AC_MTP="${AC_MTP:-websocket}"

echo "[entrypoint] MAC:         ${AC_MAC_ADDR}"
echo "[entrypoint] Endpoint ID: ${AC_ENDPOINT_ID}"
echo "[entrypoint] WS URL:      ${AC_WS_URL}"
echo "[entrypoint] Controller:  ${AC_CONTROLLER_ID}"

# ── Generate dev TLS certificates ─────────────────────────────────────────────
# In production these come from step-ca / provisioned by ac-server.
# For dev we generate a self-signed CA and client cert so ac-client starts.
CA_KEY=${CONF_DIR}/dev-ca.key
CA_CRT=${CONF_DIR}/ca.crt
CLIENT_KEY=${CONF_DIR}/client.key
CLIENT_CRT=${CONF_DIR}/client.crt
INIT_KEY=${CONF_DIR}/init/client.key
INIT_CRT=${CONF_DIR}/init/client.crt

if [ ! -f "${CA_CRT}" ]; then
    echo "[entrypoint] Generating dev CA..."
    openssl genrsa -out "${CA_KEY}" 2048 2>/dev/null
    openssl req -new -x509 -key "${CA_KEY}" -out "${CA_CRT}" -days 3650 \
        -subj "/CN=OptimACS-Dev-CA/O=Dev" 2>/dev/null
fi

if [ ! -f "${CLIENT_CRT}" ]; then
    echo "[entrypoint] Generating dev client cert..."
    openssl genrsa -out "${CLIENT_KEY}" 2048 2>/dev/null
    openssl req -new -key "${CLIENT_KEY}" \
        -subj "/CN=${AC_ENDPOINT_ID}/O=Dev" 2>/dev/null \
        | openssl x509 -req -CA "${CA_CRT}" -CAkey "${CA_KEY}" \
          -CAcreateserial -out "${CLIENT_CRT}" -days 3650 2>/dev/null
fi

# Init certs (same as client for dev — prod gets separate provisioning certs)
[ -f "${INIT_CRT}" ] || cp "${CLIENT_CRT}" "${INIT_CRT}"
[ -f "${INIT_KEY}" ] || cp "${CLIENT_KEY}" "${INIT_KEY}"

# ── Write config file ─────────────────────────────────────────────────────────
cat > "${CONF_FILE}" << EOF
# ac-client dev configuration — auto-generated by entrypoint
# Edit environment variables in docker-compose.dev.yml to override.

# Device identity
mac_addr        = ${AC_MAC_ADDR}
arch            = ${AC_ARCH}
sys_model       = ${AC_SYS_MODEL}
usp_endpoint_id = ${AC_ENDPOINT_ID}

# TLS certificates
ca_file         = ${CA_CRT}
cert_file       = ${CLIENT_CRT}
key_file        = ${CLIENT_KEY}
init_cert       = ${INIT_CRT}
init_key        = ${INIT_KEY}
cert_dir        = ${CONF_DIR}

# USP / TR-369 controller
controller_id   = ${AC_CONTROLLER_ID}
mtp             = ${AC_MTP}
ws_url          = ${AC_WS_URL}
EOF

if [ -n "${AC_MQTT_URL}" ]; then
    echo "mqtt_url        = ${AC_MQTT_URL}" >> "${CONF_FILE}"
fi

cat >> "${CONF_FILE}" << EOF

# Runtime
daemonize       = false
log_syslog      = false
update_interval = 60
status_interval = 300
fw_dir          = /tmp/firmware
img_dir         = /tmp/cam
EOF

echo "[entrypoint] Config written to ${CONF_FILE}"

# ── Start ac-client ───────────────────────────────────────────────────────────
export RUST_LOG="${AC_LOG_LEVEL}"
exec /usr/bin/ac-client -c "${CONF_FILE}" --stderr
